DROP TABLE IF EXISTS Employee;

CREATE TABLE Employee (
  ID         INTEGER IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME  VARCHAR(100) NOT NULL,
  TITLE      VARCHAR(100) NOT NULL,
  EMAIL      VARCHAR(50) NOT NULL
);
